from __future__ import annotations

from fastapi import FastAPI

from .schemas import (
    BuildTestDataCleanupResponse,
    BulkUpsertResult,
    MaintenanceReport,
    MaintenanceReportDetail,
    MaintenanceReportEntry,
    MemoryOut,
    PolicyRegistry,
    SearchResult,
    SyncCheckResponse,
    TestDataHygieneReport,
)


def register_crud_routes(app: FastAPI, handlers) -> None:
    app.add_api_route(
        "/api/memories",
        handlers.create_memory,
        methods=["POST"],
        response_model=MemoryOut,
        status_code=201,
    )
    app.add_api_route(
        "/api/memories/bulk",
        handlers.create_memories_bulk,
        methods=["POST"],
        response_model=list[MemoryOut],
        status_code=201,
    )
    app.add_api_route(
        "/api/memories/bulk-upsert",
        handlers.bulk_upsert_memories,
        methods=["POST"],
        response_model=BulkUpsertResult,
        status_code=200,
    )
    app.add_api_route(
        "/api/memories/{memory_id}",
        handlers.read_memory,
        methods=["GET"],
        response_model=MemoryOut,
    )
    app.add_api_route(
        "/api/memories",
        handlers.read_memories,
        methods=["GET"],
        response_model=list[MemoryOut],
    )
    app.add_api_route(
        "/api/memories/search",
        handlers.search,
        methods=["POST"],
        response_model=list[SearchResult],
    )
    app.add_api_route(
        "/api/memories/{memory_id}",
        handlers.update,
        methods=["PUT"],
        response_model=MemoryOut,
    )
    app.add_api_route(
        "/api/memories/{memory_id}",
        handlers.delete,
        methods=["DELETE"],
        status_code=200,  # Changed from 204 to allow response body
        response_model=dict,  # Return {"deleted": true} or similar
    )
    app.add_api_route(
        "/api/memories/sync-check",
        handlers.check_sync_endpoint,
        methods=["POST"],
        response_model=SyncCheckResponse,
    )
    app.add_api_route(
        "/api/admin/maintain",
        handlers.maintain,
        methods=["POST"],
        response_model=MaintenanceReport,
    )
    app.add_api_route(
        "/api/admin/policy-registry",
        handlers.read_policy_registry,
        methods=["GET"],
        response_model=PolicyRegistry,
    )
    app.add_api_route(
        "/api/admin/policy-registry",
        handlers.update_policy_registry,
        methods=["PUT"],
        response_model=PolicyRegistry,
    )
    app.add_api_route(
        "/api/admin/maintain/reports",
        handlers.maintain_reports,
        methods=["GET"],
        response_model=list[MaintenanceReportEntry],
    )
    app.add_api_route(
        "/api/admin/maintain/reports/{report_id}",
        handlers.maintain_report_detail,
        methods=["GET"],
        response_model=MaintenanceReportDetail,
    )
    app.add_api_route(
        "/api/admin/test-data/report",
        handlers.test_data_hygiene_report,
        methods=["GET"],
        response_model=TestDataHygieneReport,
    )
    app.add_api_route(
        "/api/admin/test-data/cleanup-build",
        handlers.cleanup_build_test_data,
        methods=["POST"],
        response_model=BuildTestDataCleanupResponse,
    )
    app.add_api_route(
        "/api/memories/export",
        handlers.export,
        methods=["POST"],
    )
